export const ORDER_GET_ALL_ORDERS_REQUEST = 'ORDER_GET_ALL_ORDERS_REQUEST'
export const ORDER_GET_ALL_ORDERS_SUCCESS = 'ORDER_GET_ALL_ORDERS_SUCCESS'
export const ORDER_GET_ALL_ORDERS_FAIL = 'ORDER_GET_ALL_ORDERS_FAIL'